/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_viila_android_linearallocfix_lib_LinearAllocFix */

#ifndef _Included_info_viila_android_linearallocfix_lib_LinearAllocFix
#define _Included_info_viila_android_linearallocfix_lib_LinearAllocFix
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     info_viila_android_linearallocfix_lib_LinearAllocFix
 * Method:    current
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_info_viila_android_linearallocfix_lib_LinearAllocFix_current
  (JNIEnv *, jobject);

/*
 * Class:     info_viila_android_linearallocfix_lib_LinearAllocFix
 * Method:    debug
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_info_viila_android_linearallocfix_lib_LinearAllocFix_hack
  (JNIEnv *, jobject);

/*
 * Class:     info_viila_android_linearallocfix_lib_LinearAllocFix
 * Method:    hack
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_info_viila_android_linearallocfix_lib_LinearAllocFix_debug
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
